#!/bin/bash

if [[ -z "$1" ]]; then
    echo
    read -p "Which option do you want to call ? : " OPT
    echo
else
    OPT="$1" 
fi

case $OPT in
    -add) FUNC="AddRepository" ;;
    -rm) FUNC="RemoveRepository" ;;
    -help) echo -e "Usage prog -repo <option> <category_name> <repository_name>\n\n
        Options:\n\n
        -add  -> Add a repository to to a certain category\n
        -rm   -> Remove a repository to to a certain category\n"
        exit 0
        ;;
    *)  echo -e "\nInvalid parameter. Try again" 
        exit 1 
        ;;
esac

if [[ -f "$FUNC" ]]; then
    bash "Repository_Manager/src/Repository/$func" "$2" "$3" "$4"
else
    echo -e "\nFunction script $FUNC not found."
    exit 1
fi