#!/bin/bash

function Check_Choiced_Repository() {
    if [[ -f "Repository_Manager/src/.Update_Repositories/.Update_$1" ]]; then
        FUNC="$1"
    else
        echo -e "\nInvalid parameter. Try again"
        exit 1
    fi
}

PATH="GitRepositories"

if [[ -z "$1" ]]; then
    echo
    read -p "Which type of update do you want to do ? :  " CHOICE
else
    CHOICE="$1"
fi

if [[ ! -d $PATH ]]; then
    mkdir -p $PATH
fi

case $CHOICE in
    -a) FUNC=All ;;
    --all) FUNC=All ;;
    -help) echo "\nUsage: prog -upt <option>\n\n
        Options: \n\n
        -a    -> Update all your repositories\n
        --all -> Update all your repositories"
        exit 0
        ;;
    *) Check_Choiced_Repository $CHOICE
esac

if [[ -f "Repository_Manager/src/.Update_Repositories/.Update_$FUNC" ]]; then
    echo
    bash "Repository_Manager/src/.Update_Repositories/.Update_$FUNC" "$2" "$3"
else
    echo -e "\nFunction script Repository_Manager/src/.Update_Repositories/.Update_$FUNC not found."
    exit 1
fi